name: time_range_sheet_widget_example
description: Example app demonstrating the time_range_sheet_widget package.
publish_to: 'none'
version: 0.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  time_range_sheet_widget:
    path: ../
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 
